#!/bin/sh
#
# PROVIDE: snort
# REQUIRE: DAEMON
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable snort:
#
# snort_enable="YES"
# snort_flags=""
#
# You can also set the snort configuration directory with:
#
# snort_confdir="/usr/local/etc/snort"

. /etc/rc.subr

name="snort"
rcvar=snort_enable
command="/usr/local/bin/snort"
snort_confdir=${snort_confdir:-"/usr/local/etc/snort"}
pidfile="/var/run/snort.pid"
required_files="${snort_confdir}/snort.lua"
command_args="-c ${snort_confdir}/snort.lua -i hn0 -D -l /var/log/snort -u root -g wheel "

# start_cmd="${command} ${command_args} > /dev/null 2>&1 & echo \$! > ${pidfile}"
# stop_cmd="kill \$(cat ${pidfile})"

load_rc_config $name
run_rc_command "$1"
