#!/bin/sh
#
# PROVIDE: snort3
# REQUIRE: NETWORKING
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable snort3:
#
# snort_enable="YES"
#

. /etc/rc.subr

name="snort3"
rcvar=snort_enable

# snort -c /usr/local/etc/snort/snort.lua 
# -R /usr/local/etc/snort/rules/smbghost.rules 
# -r ~/devopsScripts/SMBGHOST/SMBGhost.pcap' 
# -l /var/log/snort > snort_check.sh'

load_rc_config $name

: ${snort_enable:="NO"}
: ${snort_interface:="hn0"}
: ${snort_conf:="/usr/local/etc/snort/snort.lua"}
: ${snort_log:="/var/log/snort"}
: ${smbghost_rules="/usr/local/etc/snort/rules/smbghost.rules"}

command="/usr/local/bin/snort"
command_args="-c ${snort_conf} -i -D -l ${snort_log} -R ${smbghost_rules}"
# command_args="-c ${snort_conf} -i ${snort_interface} -D -l ${snort_log} -R ${smbghost_rules}"

pidfile="/var/run/${name}.pid"
logfile="/var/log/snort/snortD.log"

start_cmd="${command} ${command_args} > /dev/null 2>&1 & echo \$! > ${pidfile}"
stop_cmd="kill \$(cat ${pidfile})"


run_rc_command "$1"
