#!/bin/sh
#
# PROVIDE: snort
# REQUIRE: DAEMON
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable snort:
#
# snort_enable="YES"
# snort_flags=""
#
# You can also set the snort configuration directory with:
#
# snort_confdir="/usr/local/etc/snort"

. /etc/rc.subr

name="snort"
rcvar=snort_enable
command="/usr/local/bin/snort"
snort_confdir=${snort_confdir:-"/usr/local/etc/snort"}
pidfile="/var/run/snort.pid"
required_files="${snort_confdir}/snort.lua"
# command_args="-c ${snort_confdir}/snort.lua -D -i hn0 -l /var/log/snort -u root"
command_args="-c ${snort_confdir}/snort.lua -D -l /var/log/snort -u root -g wheel --daq afpacket --daq-mode inline --daq-var snaplen=1518 --daq-var em0 --daq-var em1"

load_rc_config $name
run_rc_command "$1"
