#!/bin/sh
#
# PROVIDE: snort
# REQUIRE: DAEMON
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable snort:
#
# snort_enable="YES"
# snort_flags=""
#
# You can also set the snort configuration directory with:
#
# snort_confdir="/usr/local/etc/snort"

. /etc/rc.subr

name="snort"
rcvar=snort_enable
command="/usr/local/bin/snort"
snort_confdir=${snort_confdir:-"/usr/local/etc/snort"}
pidfile="/var/run/snort.pid"
required_files="${snort_confdir}/snort.lua"
# command_args="-c ${snort_confdir}/snort.lua --daq netmap --daq-mode passive --daq-var snaplen=1518  --daq-var txcsum=on --daq-var rxcsum=on -i hn0:hn1 -D -l /var/log/snort -u root -g wheel "
# command_args="-c ${snort_confdir}/snort.lua --daq netmap --daq-mode inline --daq-var txcsum=on --daq-var rxcsum=on -i hn0:hn1 -D -l /var/log/snort -u root -g wheel "
# command_args="-c ${snort_confdir}/snort.lua --daq netmap --daq-var mem=2048 --daq-mode inline -i bridge0:hn1 -D -l /var/log/snort -u root -g wheel "
# command_args="-c ${snort_confdir}/snort.lua --daq netmap --daq-var mem=2048 --daq-mode inline -i hn0:hn1 -D -l /var/log/snort -u root -g wheel "
# command_args="-c ${snort_confdir}/snort.lua --daq netmap --daq-var mem=2048 --daq-mode inline -i bridge0:bridge1 -D -l /var/log/snort -u root -g wheel "
command_args="-c ${snort_confdir}/snort.lua --daq netmap --daq-var debug --daq-var port=netmap:hn1 -i hn0:hn1 -D -l /var/log/snort -u root -g wheel -Q"

# command_args="-c ${snort_confdir}/snort.lua --daq netmap --daq-mode inline -i bridge0 -D -l /var/log/snort -u root -g wheel "
load_rc_config $name
run_rc_command "$1"
